# Generated by Django 5.2 on 2025-05-06 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='author',
        ),
        migrations.RemoveField(
            model_name='update',
            name='project',
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
