# Generated by Django 5.2 on 2025-05-07 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_update_author_remove_update_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='current_spending',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current project spending', max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='current_worker_count',
            field=models.IntegerField(default=0, help_text='Current number of assigned workers'),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Technical details about the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_requirements',
            field=models.TextField(blank=True, help_text='Required equipment for the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_workers',
            field=models.IntegerField(default=0, help_text='Approximate number of workers needed'),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mitigation_strategies',
            field=models.TextField(blank=True, help_text='Strategies to mitigate identified risks', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='resource_allocation',
            field=models.TextField(blank=True, help_text='Resource allocation plan', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_assessment',
            field=models.TextField(blank=True, help_text='Detailed risk assessment for the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='supply_chain_requirements',
            field=models.TextField(blank=True, help_text='Key supply chain requirements', null=True),
        ),
        migrations.AddField(
            model_name='projectworker',
            name='performance_rating',
            field=models.FloatField(blank=True, help_text='Worker performance rating (0-5)', null=True),
        ),
        migrations.AddField(
            model_name='projectworker',
            name='role_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectworker',
            name='skills',
            field=models.TextField(blank=True, help_text="Worker's relevant skills", null=True),
        ),
        migrations.CreateModel(
            name='ProjectSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('materials_provided', models.TextField(help_text='List of materials this supplier provides')),
                ('reliability_score', models.FloatField(default=0.0, help_text='Supplier reliability score (0-100)')),
                ('lead_time_days', models.IntegerField(default=0, help_text='Average lead time in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completion_percentage', models.IntegerField(default=0)),
                ('is_milestone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_events', to='projects.projecttimeline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='projects.project')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('risk_category', models.CharField(choices=[('supply_chain', 'Supply Chain'), ('workforce', 'Workforce'), ('financial', 'Financial'), ('weather', 'Weather/Environmental'), ('technical', 'Technical'), ('safety', 'Safety'), ('regulatory', 'Regulatory'), ('other', 'Other')], default='other', max_length=20)),
                ('probability', models.FloatField(default=0.0, help_text='Probability of occurrence (0-1)')),
                ('impact', models.FloatField(default=0.0, help_text='Impact severity (0-10)')),
                ('mitigation_plan', models.TextField()),
                ('contingency_plan', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
        ),
    ]
