# Generated by Django 5.2 on 2025-05-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_update',
            field=models.BooleanField(default=False, help_text='Flag to indicate this is a project update via chat'),
        ),
    ]
